name: Java CI with Checkstyle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Checkstyle
      run: |
        echo "Running Checkstyle on Java files..."
        java -jar checkstyle.jar -c checkstyle.xml *.java
        # 👆 If you move your files into src/, replace with:
        # java -jar checkstyle.jar -c checkstyle.xml src
