name: Run StoreFront Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile and Run Tests
        run: |
          # Create output directory for class files
          mkdir -p out
          
          # Compile all Java files with classpath including JUnit + Mockito JARs
          javac -cp ".:lib/junit-platform-console-standalone-1.9.3.jar:lib/mockito-core-5.4.0.jar" -d out *.java
          
          # Run all tests using the JUnit Console Launcher
          java -jar lib/junit-platform-console-standalone-1.9.3.jar -cp "out:lib/mockito-core-5.4.0.jar" --scan-class-path
