name: Run StoreFront Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile and Run Tests
        run: |
          mkdir -p out

          # Define classpath including all libraries
          CP=".:lib/junit-platform-console-standalone-1.9.3.jar:lib/mockito-core-5.4.0.jar:lib/byte-buddy-1.14.4.jar:lib/byte-buddy-agent-1.14.4.jar"

          # Compile Java files
          javac -cp "$CP" -d out *.java

          # Run JUnit tests
          java -jar lib/junit-platform-console-standalone-1.9.3.jar -cp "out:$CP" --scan-class-path
